/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_windjammer_zetascale_ZSNativeThread */

#ifndef _Included_com_windjammer_zetascale_ZSNativeThread
#define _Included_com_windjammer_zetascale_ZSNativeThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_windjammer_zetascale_ZSNativeThread
 * Method:    ZSInitPerThreadState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_windjammer_zetascale_ZSNativeThread_ZSInitPerThreadState
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_windjammer_zetascale_ZSNativeThread
 * Method:    ZSReleasePerThreadState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_windjammer_zetascale_ZSNativeThread_ZSReleasePerThreadState
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
