/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_windjammer_zetascale_ZSNative */

#ifndef _Included_com_windjammer_zetascale_ZSNative
#define _Included_com_windjammer_zetascale_ZSNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_windjammer_zetascale_ZSNative
 * Method:    ZSLoadProperties
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_windjammer_zetascale_ZSNative_ZSLoadProperties
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_windjammer_zetascale_ZSNative
 * Method:    ZSSetProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_windjammer_zetascale_ZSNative_ZSSetProperty
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_windjammer_zetascale_ZSNative
 * Method:    ZSInit
 * Signature: (Lcom/windjammer/zetascale/ZSState;)I
 */
JNIEXPORT jint JNICALL Java_com_windjammer_zetascale_ZSNative_ZSInit
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_windjammer_zetascale_ZSNative
 * Method:    ZSShutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_windjammer_zetascale_ZSNative_ZSShutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_windjammer_zetascale_ZSNative
 * Method:    ZSGetProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_windjammer_zetascale_ZSNative_ZSGetProperty
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
