/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_windjammer_zetascale_ZSNativeUtils */

#ifndef _Included_com_windjammer_zetascale_ZSNativeUtils
#define _Included_com_windjammer_zetascale_ZSNativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_windjammer_zetascale_ZSNativeUtils
 * Method:    ZSErrorString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_windjammer_zetascale_ZSNativeUtils_ZSErrorString
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
