/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_windjammer_zetascale_ZSNativeContainer */

#ifndef _Included_com_windjammer_zetascale_ZSNativeContainer
#define _Included_com_windjammer_zetascale_ZSNativeContainer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_windjammer_zetascale_ZSNativeContainer
 * Method:    ZSLoadCntrPropDefaults
 * Signature: (Lcom/windjammer/zetascale/type/ContainerProperty;)I
 */
JNIEXPORT jint JNICALL Java_com_windjammer_zetascale_ZSNativeContainer_ZSLoadCntrPropDefaults
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_windjammer_zetascale_ZSNativeContainer
 * Method:    ZSOpenContainer
 * Signature: (JLjava/lang/String;ILcom/windjammer/zetascale/type/ContainerProperty;)I
 */
JNIEXPORT jint JNICALL Java_com_windjammer_zetascale_ZSNativeContainer_ZSOpenContainer
  (JNIEnv *, jclass, jlong, jstring, jint, jobject);

/*
 * Class:     com_windjammer_zetascale_ZSNativeContainer
 * Method:    ZSCloseContainer
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_windjammer_zetascale_ZSNativeContainer_ZSCloseContainer
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_windjammer_zetascale_ZSNativeContainer
 * Method:    ZSDeleteContainer
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_windjammer_zetascale_ZSNativeContainer_ZSDeleteContainer
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_windjammer_zetascale_ZSNativeContainer
 * Method:    ZSGetContainers
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_windjammer_zetascale_ZSNativeContainer_ZSGetContainers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_windjammer_zetascale_ZSNativeContainer
 * Method:    ZSFlushContainer
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_windjammer_zetascale_ZSNativeContainer_ZSFlushContainer
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_windjammer_zetascale_ZSNativeContainer
 * Method:    ZSGetContainerProps
 * Signature: (JJLcom/windjammer/zetascale/type/ContainerProperty;)I
 */
JNIEXPORT jint JNICALL Java_com_windjammer_zetascale_ZSNativeContainer_ZSGetContainerProps
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     com_windjammer_zetascale_ZSNativeContainer
 * Method:    ZSSetContainerProps
 * Signature: (JJLcom/windjammer/zetascale/type/ContainerProperty;)I
 */
JNIEXPORT jint JNICALL Java_com_windjammer_zetascale_ZSNativeContainer_ZSSetContainerProps
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     com_windjammer_zetascale_ZSNativeContainer
 * Method:    ZSWriteObject
 * Signature: (J[B[BJI)I
 */
JNIEXPORT jint JNICALL Java_com_windjammer_zetascale_ZSNativeContainer_ZSWriteObject
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_windjammer_zetascale_ZSNativeContainer
 * Method:    ZSReadObject
 * Signature: (J[BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_windjammer_zetascale_ZSNativeContainer_ZSReadObject
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     com_windjammer_zetascale_ZSNativeContainer
 * Method:    ZSDeleteObject
 * Signature: (J[BJ)I
 */
JNIEXPORT jint JNICALL Java_com_windjammer_zetascale_ZSNativeContainer_ZSDeleteObject
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     com_windjammer_zetascale_ZSNativeContainer
 * Method:    ZSFlushObject
 * Signature: (J[BJ)I
 */
JNIEXPORT jint JNICALL Java_com_windjammer_zetascale_ZSNativeContainer_ZSFlushObject
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     com_windjammer_zetascale_ZSNativeContainer
 * Method:    ZSFlushCache
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_windjammer_zetascale_ZSNativeContainer_ZSFlushCache
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
